/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaowei_ndkcpp_NDKUtils */

#ifndef _Included_com_xiaowei_ndkcpp_NDKUtils
#define _Included_com_xiaowei_ndkcpp_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaowei_ndkcpp_NDKUtils
 * Method:    CPPhhh
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaowei_ndkcpp_NDKUtils_CPPhhh
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
