/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaowei_ndkcpp_NDKCppInterface */

#ifndef _Included_com_xiaowei_ndkcpp_NDKCppInterface
#define _Included_com_xiaowei_ndkcpp_NDKCppInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaowei_ndkcpp_NDKCppInterface
 * Method:    executeCppConst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaowei_ndkcpp_NDKCppInterface_executeCppConst(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_xiaowei_ndkcpp_NDKCppInterface_executeCppPointer(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_xiaowei_ndkcpp_NDKCppInterface_executeCppConstRef(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_xiaowei_ndkcpp_NDKCppInterface_executeCppInlineFunc(JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
