/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaowei_ndkcpp_NDKCpp */

#ifndef _Included_com_xiaowei_ndkcpp_NDKCpp
#define _Included_com_xiaowei_ndkcpp_NDKCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaowei_ndkcpp_NDKCpp
 * Method:    callCppConstruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaowei_ndkcpp_NDKCpp_callCppConstruct
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL
Java_com_xiaowei_ndkcpp_NDKCpp_callCppNewOrDelete(JNIEnv *env, jobject thiz);
#ifdef __cplusplus
}
#endif
#endif
