/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaowei_ndkcpp_NDKCInterface */

#ifndef _Included_com_xiaowei_ndkcpp_NDKCInterface
#define _Included_com_xiaowei_ndkcpp_NDKCInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaowei_ndkcpp_NDKCInterface
 * Method:    executeCConst
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaowei_ndkcpp_NDKCInterface_executeCConst
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
