/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaowei_ndkcpp_NDKCppSecondInterface */

#ifndef _Included_com_xiaowei_ndkcpp_NDKCppSecondInterface
#define _Included_com_xiaowei_ndkcpp_NDKCppSecondInterface
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_xiaowei_ndkcpp_NDKCppSecondInterface_executeCppConstruct(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_xiaowei_ndkcpp_NDKCppSecondInterface_executeCppDestrcut(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_xiaowei_ndkcpp_NDKCppSecondInterface_executeCppCopyFunc(JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
